// Generated by CoffeeScript 1.10.0
(function() {
  var config;

  config = require('./config.json');

  module.exports = {
    getConfig: function() {
      return config[process.env.ENV];
    }
  };

}).call(this);

//# sourceMappingURL=config.js.map
