// Generated by CoffeeScript 1.10.0
(function() {
  var Config, Singleton, mongoose;

  mongoose = require('mongoose');

  Config = require('./config');

  module.exports = Singleton = (function() {
    var PrivateMySQL, instance;

    function Singleton() {}

    instance = null;

    PrivateMySQL = (function() {
      function PrivateMySQL() {}

      PrivateMySQL.prototype.init = function() {
        this.connection = new MySQL(Config.getConfig());
        return this.connection.connect();
      };

      return PrivateMySQL;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new PrivateMySQL();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
