// Generated by CoffeeScript 1.10.0
(function() {
  var Singleton, config, mongoose;

  mongoose = require('mongoose');

  config = require('./config.json');

  mongoose = require('mongoose');

  module.exports = Singleton = (function() {
    var PrivateDb, instance;

    function Singleton() {}

    instance = null;

    PrivateDb = (function() {
      function PrivateDb() {}

      PrivateDb.prototype.init = function(done) {
        mongoose.connect('mongodb://localhost/codepaste');
        this.db = mongoose.connection;
        this.db.on('error', function(error) {
          return done(error);
        });
        return this.db.on('open', done);
      };

      return PrivateDb;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new PrivateDb();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
