// Generated by CoffeeScript 1.10.0
(function() {
  var zombie;

  zombie = require('zombie');

  module.exports = function() {
    return this.browser = new zombie;
  };

}).call(this);

//# sourceMappingURL=world.js.map
