// Generated by CoffeeScript 1.10.0
(function() {
  var Singleton, async, email, server;

  async = require('async');

  email = require('emailjs');

  server = email.server.connect({
    user: process.env.USER,
    password: process.env.PASS,
    host: 'smtp.gmail.com',
    ssl: true
  });

  module.exports = Singleton = (function() {
    var Mail, instance;

    function Singleton() {}

    instance = null;

    Mail = (function() {
      function Mail() {}

      Mail.prototype.send = function(opts, done) {
        if (!(opts.user && opts.message && opts.title)) {
          return done(new Error());
        }
        return async.waterfall([
          (function(_this) {
            return function(next) {
              var mailOpts;
              mailOpts = {
                from: process.env.USER,
                to: process.env.USER + "@gmail.com",
                subject: "Codepaste: " + opts.title,
                text: _this._getText(opts)
              };
              return server.send(mailOpts, next);
            };
          })(this), function(response, next) {
            var mailOpts;
            mailOpts = {
              from: process.env.USER + "@gmail.com",
              to: opts.user.user.email,
              subject: 'Codepaste',
              text: 'Your message has been sent.'
            };
            return server.send(mailOpts, next);
          }
        ], done);
      };

      Mail.prototype._getText = function(opts) {
        var now, user;
        now = new Date();
        user = JSON.stringify(opts.user);
        return now + " " + user + " " + opts.message;
      };

      return Mail;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new Mail();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
