// Generated by CoffeeScript 1.10.0
(function() {
  var Singleton, async, nodemailer, transporter;

  async = require('async');

  nodemailer = require('nodemailer');

  transporter = nodemailer.createTransport("smtps://" + process.env.USER + ".com:" + process.env.PASS + "@smtp.gmail.com");

  module.exports = Singleton = (function() {
    var Mail, instance;

    function Singleton() {}

    instance = null;

    Mail = (function() {
      function Mail() {}

      Mail.prototype.send = function(opts, done) {
        if (!(opts.user && opts.message && opts.title)) {
          return done(new Error());
        }
        return async.waterfall([
          (function(_this) {
            return function(next) {
              var mailOpts;
              mailOpts = {
                from: process.env.USER,
                to: process.env.USER,
                subject: "Codepaste message: " + opts.title,
                text: _this._getText(opts)
              };
              return transporter.sendMail(mailOpts, next);
            };
          })(this), (function(_this) {
            return function(next) {
              var mailOpts;
              mailOpts = {
                from: process.env.USER,
                to: opts.user.email,
                subject: 'Codepaste',
                text: 'Your message has been sent.'
              };
              return transporter.sendMail(mailOpts, next);
            };
          })(this)
        ], done);
      };

      Mail.prototype._getText = function(opts) {
        var now, user;
        now = new Date();
        user = JSON.stringify(opts.user);
        return now + "/n" + user + "/n/n" + opts.message;
      };

      return Mail;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new Mail();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
