// Generated by CoffeeScript 1.10.0
(function() {
  var Mongo, Router, Server, fs;

  fs = require('fs');

  Mongo = require('./lib/db');

  Server = require('./lib/server');

  Router = require('./lib/router');

  Mongo.get().init(function(err) {
    if (err) {
      fs.writeFileSync('./error-log', JSON.stringify(err));
      process.exit();
    }
    Server.get().init();
    return Router.get().setRoutes(Server.get().app);
  });

  module.exports = Server.get().app;

}).call(this);

//# sourceMappingURL=index.js.map
