// Generated by CoffeeScript 1.10.0
(function() {
  var Mongo, Router, Server;

  Mongo = require('./lib/db');

  Server = require('./lib/server');

  Router = require('./lib/router');

  Mongo.get().init(function(err) {
    console.log('Connected to mongo...');
    if (err) {
      console.log(err);
      process.exit();
    }
    Server.get().init();
    return Router.get().setRoutes(Server.get().app);
  });

  module.exports = Server.get().app;

}).call(this);

//# sourceMappingURL=index.js.map
