// Generated by CoffeeScript 1.10.0
(function() {
  var Router, Server;

  Server = require('./lib/server');

  Router = require('./lib/router');

  Server.get().init();

  Router.get().setRoutes(Server.get().app);

  module.exports = Server.get().app;

}).call(this);

//# sourceMappingURL=index.js.map
