// Generated by CoffeeScript 1.10.0
(function() {
  var email, mailOpts, server;

  email = require('emailjs');

  server = email.server.connect({
    user: 'd.andreev90@gmail.com',
    password: 'GoogleHardPa55',
    host: "smtp.gmail.com",
    ssl: true
  });

  mailOpts = {
    from: 'd.andreev90@gmail.com',
    to: 'd.andreev90@gmail.com',
    subject: "Codepaste message: Title",
    text: 'text'
  };

  server.send(mailOpts, function(err, res) {
    return console.log(err, res);
  });

}).call(this);

//# sourceMappingURL=testmail.js.map
