// Generated by CoffeeScript 1.10.0
(function() {
  var Response, STATUS_CODES, Tokens, express, routes;

  express = require('express');

  routes = require('../../lib/router/routes');

  Response = require('../../lib/response/index');

  STATUS_CODES = require('../../lib/constants').STATUS_CODES;

  Tokens = require('../../services').Tokens;

  module.exports = express.Router().post(routes.validate, function(req, res) {
    return Tokens.get().validateToken(req, res, function(err, token) {
      var body, ref, statusCode;
      ref = new Response(err, token, STATUS_CODES.OK), statusCode = ref.statusCode, body = ref.body;
      return res.status(statusCode).send(body);
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
