// Generated by CoffeeScript 1.10.0
(function() {
  var Response, STATUS_CODES, VIEWS, express, ref, routes;

  express = require('express');

  routes = require('../../lib/router/routes');

  Response = require('../../lib/response/index');

  ref = require('../../lib/constants'), STATUS_CODES = ref.STATUS_CODES, VIEWS = ref.VIEWS;

  module.exports = express.Router().get(routes.all, function(req, res) {
    var body, ref1, statusCode;
    ref1 = new Response(null, {}, STATUS_CODES.OK), statusCode = ref1.statusCode, body = ref1.body;
    return res.status(statusCode).render(VIEWS.INDEX, {
      url: process.env.APP_URL
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
