module.exports =
  ENVIRONMENTS:
    DEVELOPMENT: 'development'
    PRODUCTION: 'production'
    TEST: 'test'

  STATUS_CODES:
    CREATED: 201
    OK: 200
    BAD_REQUEST: 400
    INTERNAL_SERVER_ERROR: 500
    UNAUTHORIZED: 401
    NOT_FOUND: 404

  VIEWS:
    INDEX: 'index'

  MAX_NUMBER_OF_VOTES: 5

  USERS_API_URL: 'http://162.243.123.212'
