// Generated by CoffeeScript 1.10.0
(function() {
  var BadRequestError, InternalServerError, InvalidCredentialsError, InvalidTokenError, NotFoundError, PermissionDeniedError;

  module.exports = {
    BadRequestError: BadRequestError = (function() {
      function BadRequestError(message) {
        this.message = message;
        return;
      }

      return BadRequestError;

    })(),
    InternalServerError: InternalServerError = (function() {
      function InternalServerError(message) {
        this.message = message;
        return;
      }

      return InternalServerError;

    })(),
    InvalidCredentialsError: InvalidCredentialsError = (function() {
      function InvalidCredentialsError(message) {
        this.message = message;
        return;
      }

      return InvalidCredentialsError;

    })(),
    InvalidTokenError: InvalidTokenError = (function() {
      function InvalidTokenError(message) {
        this.message = message;
        return;
      }

      return InvalidTokenError;

    })(),
    NotFoundError: NotFoundError = (function() {
      function NotFoundError(message) {
        this.message = message;
        return;
      }

      return NotFoundError;

    })(),
    PermissionDeniedError: PermissionDeniedError = (function() {
      function PermissionDeniedError(message) {
        this.message = message;
        return;
      }

      return PermissionDeniedError;

    })()
  };

}).call(this);

//# sourceMappingURL=index.js.map
