// Generated by CoffeeScript 1.10.0
(function() {
  var BadRequestError, MESSAGES, Request, Response, STATUS_CODES, _, async, express, model, ref, routes, url;

  express = require('express');

  async = require('async');

  _ = require('lodash');

  url = require('url');

  model = require('../models/confirm');

  routes = require('../lib/router/routes');

  ref = require('../lib/constants'), STATUS_CODES = ref.STATUS_CODES, MESSAGES = ref.MESSAGES;

  Response = require('../lib/response');

  Request = require('../lib/request');

  BadRequestError = require('../lib/exceptions').BadRequestError;

  module.exports = express.Router().get(routes.confirm, function(req, res) {
    return async.waterfall([
      function(next) {
        var confirmationId, email;
        confirmationId = _.last(url.parse(req.url).pathname.split('/'));
        if (!confirmationId) {
          return next(new BadRequestError(MESSAGES.MISSING_CONFIRMATION_ID));
        }
        email = url.parse(req.url, true).query.email;
        if (!email) {
          return next(new BadRequestError(MESSAGES.MISSING_EMAIL));
        }
        return model.confirm(email, confirmationId, function(err, user) {
          return next(err, STATUS_CODES.OK, user);
        });
      }
    ], function(err, statusCode, body) {
      var ref1;
      ref1 = new Response(err, body, STATUS_CODES.OK), statusCode = ref1.statusCode, body = ref1.body;
      return res.status(statusCode).send(body);
    });
  });

}).call(this);

//# sourceMappingURL=confirm.js.map
