// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    healthCheck: require('./health_check'),
    index: require('./app'),
    register: require('./register'),
    login: require('./login')
  };

}).call(this);

//# sourceMappingURL=index.js.map
