// Generated by CoffeeScript 1.10.0
(function() {
  var Paste, Rating, STATUS_CODES, express, routes;

  express = require('express');

  routes = require('../../lib/router/routes');

  Paste = require('../../models/paste');

  Rating = require('../../services/rating');

  STATUS_CODES = require('../../lib/constants').STATUS_CODES;

  module.exports = express.Router().post(routes.rating, function(req, res) {
    if (!(req.body.user || req.body.pasteId || req.body.rate)) {
      return res.status(STATUS_CODES.BAD_REQUEST).json({});
    }
    return Paste.findOne({
      _id: req.body.pasteId
    }, function(err, paste) {
      if (!paste || !paste.user) {
        return res.status(STATUS_CODES.NOT_FOUND).json({});
      }
      paste = Rating.get().vote(req.body.user.user.email, req.body.paste, req.body.rate);
      return res.status(STATUS_CODES.OK).json({});
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
