// Generated by CoffeeScript 1.10.0
(function() {
  var Response, STATUS_CODES, express, routes;

  express = require('express');

  routes = require('../../lib/router/routes');

  Response = require('../../lib/response/index');

  STATUS_CODES = require('../../lib/constants').STATUS_CODES;

  module.exports = express.Router().get(routes.healthCheck, function(req, res) {
    var body, ref, statusCode;
    ref = new Response(null, {}, STATUS_CODES.OK), statusCode = ref.statusCode, body = ref.body;
    return res.status(statusCode).send(body);
  });

}).call(this);

//# sourceMappingURL=index.js.map
