// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    Users: require('./users'),
    Tokens: require('./tokens'),
    Mail: require('./mail')
  };

}).call(this);

//# sourceMappingURL=index.js.map
