// Generated by CoffeeScript 1.10.0
(function() {
  var STATUS_CODES, Singleton, healthCheck, index, login, ref, register, routes;

  routes = require('./routes');

  ref = require('../../controllers'), healthCheck = ref.healthCheck, index = ref.index, register = ref.register, login = ref.login;

  STATUS_CODES = require('../constants').STATUS_CODES;

  module.exports = Singleton = (function() {
    var Router, instance;

    function Singleton() {}

    instance = null;

    Router = (function() {
      function Router() {}

      Router.prototype.setRoutes = function(app) {
        app.all(routes.all, function(req, res, next) {
          res.header('Access-Control-Allow-Origin', '*');
          res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
          res.header('Access-Control-Allow-Headers', 'Content-type,Accept,X-Access-Token,X-Key');
          if (req.method === 'OPTIONS') {
            return res.status(STATUS_CODES.OK).end();
          }
          return next();
        });
        app.get(routes.index, index);
        app.get(routes.healthCheck, healthCheck);
        app.put(routes.register, register);
        return app.post(routes.login, login);
      };

      return Router;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new Router();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
