// Generated by CoffeeScript 1.10.0
(function() {
  var STATUS_CODES, Singleton, Tokens, healthCheck, index, login, newPaste, paste, ref, register, routes;

  routes = require('./routes');

  ref = require('../../controllers'), healthCheck = ref.healthCheck, index = ref.index, register = ref.register, login = ref.login, newPaste = ref.newPaste, paste = ref.paste;

  STATUS_CODES = require('../constants').STATUS_CODES;

  Tokens = require('../../services').Tokens;

  STATUS_CODES = require('../../lib/constants').STATUS_CODES;

  module.exports = Singleton = (function() {
    var Router, instance;

    function Singleton() {}

    instance = null;

    Router = (function() {
      function Router() {}

      Router.prototype.setRoutes = function(app) {
        app.all(routes.all, function(req, res, next) {
          res.header('Access-Control-Allow-Origin', '*');
          res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
          res.header('Access-Control-Allow-Headers', 'Content-type,Accept,X-Access-Token,X-Key');
          if (req.method === 'OPTIONS') {
            return res.status(STATUS_CODES.OK).end();
          }
          return next();
        });
        app.get(routes.index, index);
        app.get(routes.healthCheck, healthCheck);
        app.put(routes.register, register);
        app.post(routes.login, login);
        app.put(routes.newPaste, newPaste);
        return app.get(routes.paste, function(req, response, next) {
          return Tokens.get().validate(req, response, function(err, res) {
            if (err || res.statusCode !== 200) {
              return response.status(STATUS_CODES.UNAUTHORIZED).json({});
            }
            return paste(req, response, next);
          });
        });
      };

      return Router;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new Router();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
