// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    index: new RegExp(/\/$/),
    all: '/*',
    healthCheck: new RegExp(/\/health-check$/),
    register: new RegExp(/\/register$/)
  };

}).call(this);

//# sourceMappingURL=routes.js.map
