// Generated by CoffeeScript 1.10.0
(function() {
  var Singleton;

  module.exports = Singleton = (function() {
    var Request, instance;

    function Singleton() {}

    instance = null;

    Request = (function() {
      function Request() {}

      Request.prototype.validateToken = function(req) {
        var authHeader, token;
        authHeader = this.getAuthHeader(req);
        if (!authHeader) {
          return false;
        }
        token = this._getTokenFromHeader(authHeader);
        if (!token) {
          return false;
        }
        return token;
      };

      Request.prototype.getAuthHeader = function(req) {
        var header;
        header = req.get('Authorization');
        if (!header) {
          return false;
        }
        return header.replace('Basic ', '').replace('Bearer ', '');
      };

      Request.prototype.getCredentialsFromHeader = function(authHeader) {
        var buffer, split;
        buffer = new Buffer(authHeader, 'base64').toString();
        split = buffer.split(':');
        return {
          username: split[0],
          password: split[1]
        };
      };

      Request.prototype._getTokenFromHeader = function(authHeader) {
        return new Buffer(authHeader, 'base64').toString();
      };

      return Request;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new Request();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
