// Generated by CoffeeScript 1.10.0
(function() {
  var Paste, Response, STATUS_CODES, Server, _, express, routes;

  express = require('express');

  _ = require('lodash');

  routes = require('../../lib/router/routes');

  Paste = require('../../models/paste');

  Response = require('../../lib/response/index');

  STATUS_CODES = require('../../lib/constants').STATUS_CODES;

  Server = require('../../lib/server');

  module.exports = express.Router().put(routes.newPaste, function(req, response) {
    var body, paste;
    body = req.body;
    body.code = body.value;
    delete body.value;
    paste = new Paste(body);
    return paste.save(function(err, paste) {
      var ref, statusCode;
      ref = new Response(err, paste, STATUS_CODES.CREATED), statusCode = ref.statusCode, body = ref.body;
      body.user = {
        username: body.user.username
      };
      _.forEach(Server.get().ws.getWss().clients, function(client) {
        return client.send(JSON.stringify({
          action: 'update'
        }));
      });
      return response.status(statusCode).json(body);
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
