// Generated by CoffeeScript 1.10.0
(function() {
  var BadRequestError, ENVIRONMENTS, InvalidTokenError, NotFoundError, PermissionDeniedError, Response, STATUS_CODES, ref, ref1;

  ref = require('../exceptions'), BadRequestError = ref.BadRequestError, NotFoundError = ref.NotFoundError, InvalidTokenError = ref.InvalidTokenError, PermissionDeniedError = ref.PermissionDeniedError;

  ref1 = require('../constants'), STATUS_CODES = ref1.STATUS_CODES, ENVIRONMENTS = ref1.ENVIRONMENTS;

  module.exports = Response = (function() {
    Response.prototype.statusCode = null;

    Response.prototype.body = null;

    function Response(err, body, successStatusCode) {
      if (err) {
        if (err instanceof BadRequestError) {
          this.statusCode = STATUS_CODES.BAD_REQUEST;
          this.body = err.message;
        } else if (err instanceof NotFoundError) {
          this.statusCode = STATUS_CODES.NOT_FOUND;
          this.body = err.message;
        } else if (err instanceof InvalidTokenError) {
          this.statusCode = STATUS_CODES.UNAUTHORIZED;
          this.body = err.message;
        } else if (err instanceof PermissionDeniedError) {
          this.statusCode = STATUS_CODES.PERMISSION_DENIED;
          this.body = err.message;
        } else {
          this.statusCode = STATUS_CODES.INTERNAL_SERVER_ERROR;
          if (process.env.ENV !== ENVIRONMENTS.PRODUCTION) {
            this.body = err.message;
          }
        }
        return;
      }
      this.body = body;
      this.statusCode = successStatusCode;
    }

    return Response;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
