// Generated by CoffeeScript 1.10.0
(function() {
  var Paste, Response, STATUS_CODES, Tokens, _, express, routes;

  express = require('express');

  _ = require('lodash');

  routes = require('../../lib/router/routes');

  Paste = require('../../models/paste');

  Response = require('../../lib/response/index');

  STATUS_CODES = require('../../lib/constants').STATUS_CODES;

  Tokens = require('../../services/tokens');

  module.exports = express.Router().get(routes.paste, function(req, res) {

    /*Tokens.get().validate req, res, (err, result) ->
      console.log 'err, res', err, res.statusCode
      return res.status(STATUS_CODES.UNAUTHORIZED).json {} if err or result.statusCode == 401
     */
    var id;
    id = _.last(req.url.split('/'));
    if (!id) {
      return res.status(STATUS_CODES.BAD_REQUEST).json({});
    }
    return Paste.findOne({
      _id: id
    }, function(err, paste) {
      var body, ref, statusCode;
      if (!paste || !paste.user) {
        return res.status(STATUS_CODES.NOT_FOUND).json({});
      }
      delete paste.user.refreshToken;
      delete paste.user.token;
      delete paste.user.user.email;
      delete paste.value;
      paste.user = paste.user.user;
      ref = new Response(err, paste, STATUS_CODES.OK), statusCode = ref.statusCode, body = ref.body;
      return res.status(statusCode).json(body);
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
