// Generated by CoffeeScript 1.10.0
(function() {
  var Paste, Response, STATUS_CODES, _, express, routes;

  express = require('express');

  _ = require('lodash');

  routes = require('../../lib/router/routes');

  Paste = require('../../models/paste');

  Response = require('../../lib/response/index');

  STATUS_CODES = require('../../lib/constants').STATUS_CODES;

  module.exports = express.Router().get(routes.paste, function(req, res) {
    var id;
    id = _.last(req.url.split('/'));
    if (!id) {
      return res.status(STATUS_CODES.BAD_REQUEST).json({});
    }
    return Paste.findOne({
      _id: id
    }, function(err, paste) {
      var body, ref, statusCode;
      if (!paste || !paste.user) {
        return res.status(STATUS_CODES.NOT_FOUND).json({});
      }
      delete paste.user.refreshToken;
      delete paste.user.token;
      delete paste.user.user.email;
      delete paste.value;
      paste.user = paste.user.user;
      paste.isMine = paste.user.email === (ref = new Response(err, paste, STATUS_CODES.OK), statusCode = ref.statusCode, body = ref.body, ref);
      return res.status(statusCode).json(body);
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
