// Generated by CoffeeScript 1.10.0
(function() {
  var Singleton, USERS_API_URL, request;

  request = require('request');

  USERS_API_URL = 'http://162.243.123.212';

  module.exports = Singleton = (function() {
    var Users, instance;

    function Singleton() {}

    instance = null;

    Users = (function() {
      function Users() {}

      Users.prototype.register = function(user, done) {
        return request({
          method: 'PUT',
          uri: USERS_API_URL + "/",
          json: user
        }, function(err, res) {
          console.log(err);
          return done(err, res);
        });
      };

      return Users;

    })();

    Singleton.get = function() {
      return instance != null ? instance : instance = new Users();
    };

    return Singleton;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
