// Generated by CoffeeScript 1.10.0
(function() {
  var Paste;

  Paste = require('./paste');

  module.exports = {
    getPastes: function(q, sort, done) {
      if (sort == null) {
        sort = {
          sort: {
            created: -1
          }
        };
      }
      return Paste.find(q, {
        'user.token': 0,
        'user.refreshToken': 0
      }, sort, done);
    }
  };

}).call(this);

//# sourceMappingURL=pastes.js.map
