// Generated by CoffeeScript 1.10.0
(function() {
  var Paste;

  Paste = require('./paste');

  module.exports = {
    getPastes: function(q, done) {
      if (q == null) {
        q = {};
      }
      return Paste.find(q, {
        'user.token': 0,
        'user.refreshToken': 0
      }, {
        sort: {
          created: -1
        }
      }, done);
    }
  };

}).call(this);

//# sourceMappingURL=pastes.js.map
