// Generated by CoffeeScript 1.10.0
(function() {
  var mongoose, pasteSchema;

  mongoose = require('mongoose');

  pasteSchema = mongoose.Schema({
    title: String,
    user: Object,
    created: {
      type: Date,
      "default": Date.now
    },
    code: String,
    mode: String
  });

  module.exports = mongoose.model('Paste', pasteSchema);

}).call(this);

//# sourceMappingURL=paste.js.map
