// Generated by CoffeeScript 1.10.0
(function() {
  var Paste, _;

  Paste = require('./paste');

  _ = require('lodash');

  module.exports = {
    getPastes: function(q, sort, pagination, done) {
      if (sort == null) {
        sort = {
          sort: {
            created: -1
          }
        };
      }
      if (pagination == null) {
        pagination = {};
      }
      _.merge(sort, pagination);
      console.log('q', q, sort);
      return Paste.find(q, {
        'user.token': 0,
        'user.refreshToken': 0
      }, sort, function(err, res) {
        console.log(err, res.length);
        return Paste.count({}, function(err, pastesCount) {
          return done(err, res, pastesCount);
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=pastes.js.map
